---
title: "「图政」实习小记"
date: "2015/09/18"
categories: [日记, 指标]
---

这两天为了整理自己的「实习资料包」，把 tower 上的东西又重新翻过了一遍，突然就有了很多感触。

如果从试用期开始算起，在图政前前后后待了有 9 个月的时间。9 个月，也许相当于人生的一百零八分之一。谁知道呢，总之并不算短也并不算长。然而，现在回想起来又觉得是一闪而过。

里面有很多零散的记忆碎片，也有很多油然升起而又不知所终的情绪。现在尝试在记忆里慢慢把它们搜寻出来，拼装组合，形成一幅记忆地图，权且当作记念。

放寒假的时候，碧旋开始带着我做军队人事调动的选题。对于一个没有建库经验且不曾接触过 excel 的人而言，第一次建库的经历无疑是漫长且有点痛苦的。

军队选题的第一个困难就是切入点。在做这个选题之前，自己对中国的军队系统基本毫无了解，只能通过在网上查阅各种资料来搭建自己关于这个方面的知识体系。

在看了大量新闻，并且基本了解了军队的层级系统之后，我和碧旋决定把选题的重心放在跨军区的人事调动上。我们试图从十八大后军队高级将领的人事调动中观察各个军区（特别是南京军区、兰州军区和济南军区，分别对应习、郭、徐）势力的消长。

但最后的数据分析证明这样的预设并不准确，南京军区出身的将领并没有在晋升上有特别抢眼的表现，兰州军区和济南军区出身的将领也并未有受到明显打压的趋势。

这样的结果并不出人意料，但多多少少让我感到困惑。我不知道在对一个领域没有结构性地了解，没有非常深刻的理解和把握之前，应该如何来设立指标？怎样才能抓住真正重要的东西，而非把时间浪费在一些没有意义的指标上？以及，在建库编码之前我们是否要有自己的一个预测呢？如果需要，那么如果数据得出的结果与预测不一致怎么办？

第二个困难就是资料的收集。军队本身是一个封闭的系统，从公开途径得到将领们的详细资料并不容易，很多军事论坛里面的信息又不足采信。

花费了无数时间在互联网的各个角落里进行搜寻，结果却差强人意。不少将领只能获得诸如籍贯、年龄、级别、军衔、所在军区等基本信息，早期的从军履历却面目模糊。一些数据的缺失也给后来的分析带来了麻烦。

另一个比较棘手的问题是指标的分类，有时候一个对象可以同时分属两个指标项。比如三大海军舰队接受海军和大军区的双重领导，再比如有将领同时兼任两个职位，这时应该把它们归在什么位置？

第三个困难就是 excel 的使用了。在真正了解 excel 的强大功能之前，我做了很多无用功，用人工的方法去做着函数能够瞬间完成的事情。因而面对着满屏单元格时常会升起一丝狂躁的感觉。

不过好在工具总是相似的，在了解了工作原理后上手并不困难。借由此次建库也算是对 excel 的功能有了一些基本的了解。

其实与工具相比，选题的切入点才是真正重要的。因为它决定了一篇报道所能够达到的深度。遗憾的是，那时的我甚或说现在的我，还远未能够达到。

毕竟，时政类的深度报道需要长时间的积淀，需要对国家的政经体制的运行逻辑有自己的洞察和剖析，然后才会对当下的选题有一个准确的预判。

第一次建库花了一个多月的时间，171 位高级将领，近 30 个细分指标，仔细数一数也有 5000 余个单元格。这里还要大大地感谢碧旋给我提了许许多多有益的建议，让我少走了不少弯路。

虽然后来选题因为敏感度的原因被《南风窗》毙掉了，虽然最终得出的结论也并不让我满意，但是建库的过程还是让我受益匪浅。可以说，建库是一种强迫自己去深入了解「结构性知识」的有益方法。

3 月份军队选题甫一结束，就开始了人大代表的选题。如果说军队调动的选题是一个人的单打独斗，人大代表的选题就是完完全全的团队协作了。5 个人，3 周时间，最终完成了 2000 多个人大代表样本的编码，形成了 1 个基础库，3 个分库。

这里面最要感谢的当然是梦冉，如果没有这样一个优秀而负责的组长，我想这样的任务量我们是没办法按时完成的。印象最深刻的是 ddl 的前一天，企业家库还有一半没有完成，梦冉和柳辛说自己三点从床上爬起来编码。

我觉得团队协作最最重要的就是成员之间彼此的信任和配合。可以说，长时间、高强度的重复性工作对于团队的每个成员都是不小的挑战。如果团队没有足够的信任感和凝聚力，是难以坚持下来的。幸运的是，大家配合的很默契，而且每个人都愿意付出。

当然，除了精力和体力上的消耗，我们在编码的过程中还遇到了许许多多的问题。首当其冲的还是分类的问题，单单是「教育程度」这个指标我们就分了 18 个类目。

学历和学位的区别，党校、函授、在职的区别，中专、大专、本科、硕士、博士的区别，可以形成无数的排列组合，感觉任何分类都无法穷尽样本。我甚至觉得事实可能是这个指标并不重要，是我们太较真了。

但是在编码中又确确实实会遇到此类棘手的问题。再比如我们做人大代表的「职业」，也有 20 余个分类，看似齐全，但是遇到一些奇怪的名目，仍然束手无策，比如火车站站长和打捞局潜水队队长应该怎么分类？孤儿院院长呢？什么样的人应该归入领导干部？

当你切切实实地去思考这些问题的时候，会发现好像所有之前认为理所当然的概念都变得模糊了。概念界定本身反而变成最困难的事情，为何如此界定？依据是什么？

第二个问题就是团队作业中的版本控制问题。编码表总是在不断变动的，因为在编码的过程中，总会遇到许许多多的新问题，因此需要通过改动编码表来容纳或者说解决这些问题。

但是异地的团队作业往往不能做到所有人同时在线，编码表和数据库的改动也不能及时通知到所有人。如果有人因为疏忽而没有注意信息，就会耗费很多无谓的时间，最终还要返工，浪费了人力成本。

另一方面，例如「最终版、最最终版、真的是最终版了、最终版2.0」之类的文件命名会给人带来认知上的混乱，最终造成整个数据库版本的混乱。要解决问题，首先要保证命名规范，其次把每一次的改动都上传到 tower 固定的讨论组而非 QQ 文件上，写清楚每次所做的改动是什么。

这样，如果之后遇到问题，就可以很容易地找回任一版本的数据库或者编码表了。这种方法其实也是借鉴了 git 的版本控制思想，只不过要麻烦一些。

该怎么评价那段做人大代表选题的日子呢？现在回想起来，其实心情很复杂。一方面，我觉得那段时间真很有收获，任务量很艰巨，我们还是按时完成了。

但是结果却让人遗憾，由于各种原因，数据库依然被无限期搁置。更令人惋惜的是，研究组好像也就此散掉了，柳辛离开了图政，子章去了新闻组。我自己的情绪也陷入了低谷，一度感到十分迷茫。

和戴玉姐打了一通很长的电话，虽然并没有解决自己的困惑，但还是决定留下来。不知道什么原因，在那之后，研究组就没有继续建库了，只是偶尔帮《南风窗》做一做报告版和文内图表，因而也就没有什么特别深刻的印象。

其实还是感觉挺遗憾的，因为自己的懒散，在图政的后半段时间里没有出什么像样的成果。转眼间就到了七月，新一轮招新结束后老人们陆陆续续都离开了，我和子章各自兼了一个多月的组长，把新人们带上正轨后也到了要离开的时刻。

在图政的九个月里有很多很多的收获。除了之前提到的业务上的提升之外，最值得庆幸的就是在图政认识了很多有趣的同龄人。我觉得人是可以从同龄人身上更好地认识自己的，特别是从与自己志趣相近的同龄人身上。

还有就是，图政让我更多地认清了一些需要面对的「现实」：有的题目并非是自己想做的，但是为了完成发稿任务又不得不做，即使觉得它毫无意义，这是一种现实。有的题目是自己想做的，但是因为自己的知识结构和能力所限，又不能做好，特别是专业性要求比较高的选题，这也是一种现实。