---
title: "R 常用包和函数汇总"
author: "Boyce"
date: '2023/03/04'
categories: [R, 清单]
execute: 
  eval: false
---

## 数据摘要和清洗

### gtExtras

数据集摘要：`gtExtras::gt_plt_summary()`，展现每个变量的描述性统计指标，并用可视化的方式展现变量的分布。

### janitor

列名清洗： `janitor::clean_names()`，将命名不一致的列名统一规范化。


## 数据图表

### waffle

华夫饼图绘制包，使用方法可见[使用 waffle package 制作华夫饼图](https://whuhzx.github.io/QuartoBlog/posts/%E4%BD%BF%E7%94%A8%20waffle%20package%20%E5%88%B6%E4%BD%9C%E5%8D%8E%E5%A4%AB%E9%A5%BC%E5%9B%BE/)。

### ggalluvial

桑基图和凹凸图绘制包，使用方法可见[使用 ggalluvial 制作桑基图和凹凸图](https://whuhzx.github.io/QuartoBlog/posts/%E4%BD%BF%E7%94%A8%20ggalluvial%20%E5%88%B6%E4%BD%9C%E6%A1%91%E5%9F%BA%E5%9B%BE%E5%92%8C%E5%87%B9%E5%87%B8%E5%9B%BE/)。

### ggwordcloud

用 ggplot 语法绘制词云，使用方法可见 [ggwordcloud: a word cloud geom for ggplot2](https://cran.r-project.org/web/packages/ggwordcloud/vignettes/ggwordcloud.html) 及 [R Charts: Word cloud in ggplot2 with ggwordcloud](https://r-charts.com/ranking/ggwordcloud/)。

## 字体处理

### systemfonts 和 showtext

在作图时找到中文字体对应的英文名，并渲染中文字体，使用方法可见[作图时如何正确渲染中文字体](https://whuhzx.github.io/QuartoBlog/posts/%E4%BD%9C%E5%9B%BE%E6%97%B6%E5%A6%82%E4%BD%95%E6%AD%A3%E7%A1%AE%E6%B8%B2%E6%9F%93%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93/)。

### ggtext

在 ggplot2 中，提供了额外的富文本使用方法（例如HTML和CSS格式的文本），可以更加灵活地格式化标签、标题和其他文本，用法可见[文档](https://github.com/wilkelab/ggtext)。

### ggfittext

可以自动调整文本大小，以适应图形布局，当需要处理密集的图形和标签时较为有用。用法可见[文档](https://wilkox.org/ggfittext)。

## 其他数据可视化组件

### hrbrthemes

ggplot 主题风格拓展，使用方法可见 [hrbrthemes：最好用的 ggplot 主题扩展包](https://whuhzx.github.io/QuartoBlog/posts/hrbrthemes%EF%BC%9A%E6%9C%80%E5%A5%BD%E7%94%A8%E7%9A%84ggplot%E4%B8%BB%E9%A2%98%E6%89%A9%E5%B1%95%E5%8C%85/)。

### gghighlight

帮助高亮图表，使用方法可见[使用 gghighlight 制图](https://whuhzx.github.io/QuartoBlog/posts/%E4%BD%BF%E7%94%A8%20gghighlight%20%E5%88%B6%E5%9B%BE/)。

### patchwork

快速组合不同图表：`p1 + p2`。使用方法详见[教程](https://patchwork.data-imaginist.com/articles/patchwork.html)。

## 其他资源

-   R 包开发可见[利用 ChatGPT 编写简单 R 包](https://whuhzx.github.io/QuartoBlog/posts/%E5%88%A9%E7%94%A8%20ChatGPT%20%E7%BC%96%E5%86%99%E7%AE%80%E5%8D%95%20R%20%E5%8C%85/)。
