---
title: "Echarts3.0 使用体验"
date: "2015/12/04"
---

昨天在微博上看到，Echarts 发布了 3.0 的 beta 版本（详见[此处](http://echarts.baidu.com/related/blog/ec3new/ec3new.html)）。在新版本中，开发团队增加了一些非常强大的功能，比如:

## 把坐标系和图表类型剥离开来

在原先的版本中，柱形图、折线图、散点图都必须要和直角坐标系进行搭配，雷达图必须和极坐标搭配，地图则是一个独立的类型。剥离开以后，就可以组合产生非常多有意思的图表。特别是可以在地理坐标系上搭配各种图表类型，想想都让人觉得兴奋。

之前一直觉得 Echarts 地图的功能太过有限，就连地理空间上的气泡图都无法实现（或许用 markpoint 可以实现，但是太过麻烦没有试过）。新版本出来以后功能就大大拓展了。

## 坐标数轴支持更多的数据类型

之前曾模仿「数读」做过一个坐标轴上的气泡图，用的是散点图的图表类型。由于散点图表现的是相关关系，因此横纵数轴的数据都必须是数值型数据。所以就需要进一步将类目数据模拟成数值数据，整个过程还是比较麻烦的。3.0 出来以后就方便多了。

## 一个 Echarts 实例中，可以同时存在多个直角坐标系

之前的版本中，每个实例只允许存在一个直角坐标系。如果要实现多个直角坐标系，就要构造很多个实例。但是这样的话加载速度会变得很慢，而且页面布局也会很麻烦。

改版后实现起来就相对容易多了，有利于我们进行数据的协同比较。《纽约时报》和《华盛顿邮报》就有很多类似的例子，例如[这里](http://www.nytimes.com/interactive/2014/02/14/sports/olympics/mens-figure-skating-jumps.html)。

## 其它

- 增强了对移动端的支持

- 加强了图表的交互效果

- 设计了新的图表类型

虽然现在推出的还只是 beta 版，但这些新功能也足以让人感到惊艳了。之前学了一个多月的 Echarts2.7，从看文档、看实例开始，到模仿《纽约时报》和「数读」的图表做了11个小demo，感觉收获很大。

毕竟刚刚接触前端不久，从学习 Echarts 的过程中也加强了自己对代码的感觉，也会试着去理解整个产品的设计理念与业务逻辑。虽然很多人吐槽 Echarts 的文档写得很差，但其实只要认认真真把文档看过几遍，大体上还是能够找到解决需求的方法的。

真心希望 Echarts 会越做越好，最终能够成为一个像 D3 那样的世界级的开源产品，甚至能够超越它。
