---
title: "如何有效地获取信息"
date: "2015/09/05"
categories: [工具]
---

实习快要结束了。按照图政的传统，老实习生要为新人们提供几场培训，把自己各个方面的心得分享给大家。

其实，与其说是培训，不如说是交流。趁着此次机会，我也正好把自己在信息搜索方面各项零碎的想法重新梳理了一番。下面的内容其实是为这次交流打的底稿。

因为准备得匆忙，内容会比较宽泛。其中提到的一些工具并没有进行深入的讲解，只是介绍了基本的功能。

我知道，一旦涉及到「工具」和「方法」，大量的案例和具体的操作步骤必不可少。否则听众或读者将很难上手，更毋宁说形成使用习惯了。但因为涉及到的工具比较多，需要花心思慢慢整理，期待之后有时间会逐一补上。

## 科学上网

越来越觉得科学上网是有效获取信息的一个必要前提。在没有形成使用习惯之前可能不会有这种感觉，但是习惯一旦养成，就会产生极大的依赖性。  

科学上网首要的好处自然是可以突破信息封锁。无论是 Twitter、Facebook，还是 BBC 、纽约时报，大量优质的英语信源都需要科学上网才能有缘得见。同样的东西，有人看得见，有人无法看见，这就是信息不对称。这种不对称在专业性越强的领域，产生的影响就越大。

科学上网的第二个好处是可以使用国外优秀的科技产品，比如之后会提到的搜索引擎和 RSS 阅读器。这些产品可以大大提高我们在信息检索和信息采集方面的效率，而国内同类型的产品并不能替代它们。

## 用好搜索引擎
### 通用性搜索引擎

虽然百度的引擎做得也不错，我们平常依靠百度能够解决多数问题。但是在技术和功能的拓展上，google 无疑要比百度优秀得多。

首先体现在搜索引擎优化上。输入一个同样的关键词，很多时候谷歌返回的前几条信息就是我们想要的，而百度可能要在第二页以后才能找到。比如前阵子因为选题需要，我要找联合国发布的「电子政务报告」，两者返回的结果质量相差巨大。

个人经验是，专业性越强的东西，谷歌返回的结果准确性越高，而百度返回的结果准确性则偏低。当然，输入的关键词本身也很重要。如果搜索结果不如意，就要不断变换关键词。平常在使用搜索引擎的时候，也要不断积累关键词，很多比较专业的领域都需要我们不断试错后才能得到较为满意的结果。

### 搜索引擎语法

和百度相比，google 有着更好的搜索引擎语法支持。具体语法及应用详见[此处](http://www.zhihu.com/question/20161362)。

我觉得这些语法中最有用的一个是双引号<code>""</code>强制进行连词检索，还有就是<code>site</code>站内搜索命令和<code>inurl</code>命令。比如我们知道联合国发布了某个报告，那么直接关键词 <code>"报告名称"  site:un.org</code>就可以轻松地在联合国网站内找到报告原文。

再比如我们要找某份政府文件。为了保证信源的权威性，文件肯定要来源于政府网站，我们可以使用<code>"文件名"+inurl:gov.cn</code>来搜索这份文件。

我之前做过一个北京人口政策方面的选题，需要查找有哪些国家部委或是其下属的事业单位在招聘公告里歧视非北京户口的毕业生，即在招聘公告中声明非北京户口就不能获得某个职位。这个时候我们就可以组合各种语法来进行检索。我所使用的检索式是<code>"北京生源" OR "北京*户口"  intitle:招聘  inurl:gov</code>。  

### google自定义搜索引擎

那假如我想把搜索范围限定在某几个网站里，是否能够通过组合多个 site 语法来实现呢？很可惜，google 并不支持这种语法组合。但是 google 有一个更为便捷和强大的功能叫做「自定义搜索引擎」。通过自定义搜索引擎，我们就能够定制专属于自己的个性化搜索。

举个例子，假如我们有这样一个需求，需要查找某个议题在哪些纸媒中已经被报道过了。 这时候我们就可以建立一个「纸质媒体」的搜索引擎，把《财新周刊》、《南风窗》、《凤凰周刊》、《中国新闻周刊》、《财经》等纸媒的官网域名都添加到自定义搜索引擎里，然后保存起来。

之后在这个自定义搜索引擎页面进行搜索，搜索结果就会限定在你所设定的几个网站内，并且以后随时都可以使用。这比一个个网站地查要快速得多，也方便得多。

运用同样的方法，我们可以建立自己关注的某个议题库、影视资源搜索库、软件资源搜索库等等，大大提高自己的搜索效率。

### 专门性搜索引擎（数据库）

虽然像 google 这样的搜索引擎给我们提供了极大的便利，但是当我们需要查找一些比较冷僻的文件和资源时，通用性搜索引擎就未必能够找到了。

比如要查找某条具体的法律法规或者地方性政策，我们可以去[北大法宝](http://pkulaw.cn/)进行检索；再比如需要查找某份行业年鉴或者综合性年鉴，我们可以去中国知网的[年鉴数据库](http://tongji.cnki.net/kns55/navi/navidefault.aspx)进行检索。

要知道什么时候应该查找什么数据库，一是要靠平时的积累，同时也可以去各大学图书馆网站下熟悉各类数据库。比如[武大图书馆](http://www.lib.whu.edu.cn/web/dzzy/index.asp)和[北大图书馆](http://dbnav.lib.pku.edu.cn/)，购买的数据库都非常丰富。

## 用RSS聚合信息

RSS 的全称为 Really Simple Syndication，是一种简易的信息聚合工具。

简单来讲，假如我们需要长期跟踪某个网站的消息，但是又不想每天都到该网站上查看更新，因为那样太耗费时间和精力。

这种情况下，我们就可以利用 RSS 阅读器定制该网站的信息。只要该网站有更新，RSS 服务器就会自动抓取更新信息，并将更新内容以摘要或者全文的形式推送到我们的个人阅读器上。

假设我有这么一个需求，需要监控武汉大学文史哲三院的学术讲座信息。那么这个时候，我们就可以在每个院系官网的「学术信息」栏目下抓取页面到订阅源上，保证自己能够在第一时间得到这些消息。

再比如我们平常做数据监控，皮尤研究中心和经济学人智库等研究机构可能会不定期的发布一些报告。如果想要第一时间获取这些报告，最好的方式也是把它当成自己 RSS 阅读器的一个订阅源。

但是有的时候某些网站并不会主动提供 RSS 订阅，一般的阅读器也无法自动抓取页面。这个时候就需要我们自己配合一些工具来自行抓取，比如 feed43。这就需要我们稍微懂一些 html 语言和正则表达式了。