---
title: "又是找资料"
date: "2016/03/02"
categories: ["工具"]
---

这几天实习的时候，编辑部给派了一个任务，让我帮袁凌老师找资料。

一开始还是挺亢奋的，结果找了三四天，在电脑上泡了十多个小时，还特地跑了一次首都图书馆，依然理不清头绪。甚至一度怀疑自己到底会不会找资料。看上去似乎信息检索的方法都懂，但是真正找起来，脑子里却是一团浆糊。

袁老师在做的是一个关于北京市小商品交易市场变迁与小商贩生存境况的选题。需要我帮他找北京近年来有哪些知名的小商品交易市场拆迁或者关停了，它们的市场规模和关停的时间节点。另外还要找北京市政府限制摊贩经商的法规政策。

后一个需求简单一些。先看相关新闻报道，把报道里提到的政策法规以时间顺序做一个梳理。然后再用「北大法宝数据库」，以「摊位」、「摊贩」、「商品交易市场」、「集贸市场」等关键词进行全文检索。检索范围限制在「地方法规」和「北京」，把所有结果过一遍，挑出有用的即可。基本上不会遗漏重要信息。

另一个需求就有些麻烦了。首先要确定北京有哪些「知名」的商品交易市场或批发市场。这就涉及到「个案」，我这个外来人自然毫无头绪。特意咨询了另一个来自北京的实习生，她说了四五个地点，我一一记下，但不想也知道这肯定不全。

我的第一个想法是，要想拿到齐全的商品市场和批发市场名称以及它们的具体规模，得找工商局，他们或许有完整的名录。结果在北京市工商局的官网上并没有找到，遂放弃。

然后想既然是「被拆迁的小商品市场」，国土资源局和住建局网站或许会有信息，结果依旧没找到。

接着又打统计资料的主意，查了北京市的社会经济统计年鉴。发现有相关指标，但是只有小商品交易市场的数量统计，没有具体名称和规模。

1995年的北京市年鉴倒是有「成交额超亿元集贸市场情况」这么一个附录，里面有各个成交额超过一亿元的集贸市场的具体信息，但是时间太久远了没办法用。

令人感到奇怪的是，1995 年之前和 95 年之后都没有这么一个附录。不知道为何在 95 年就突然出现了，然后又消失了。感觉莫名其妙，统计没有一点连续性。

依旧不死心。跑到首都图书馆，翻了各种奇奇怪怪的年鉴和史志。还是没有发现有用的信息。现在才晓得，原来政府部门出的所谓「年鉴」，就是把部门里一年的新闻通稿通通罗列在一起。没有当年下发的文件和其它任何有价值的信息。

发现官方渠道基本不可能之后，又开始找论文，从知网上下载了十多篇论文，浏览完后依旧没有找到有用的信息。

于是有点绝望了。只能回到 google，重新搜相关的新闻报道。但是问题在于，没有具体的名称，只用「商品市场 OR 批发市场 拆迁」这类关键词组合，得到的结果要么是动批要么是官批、天意、大红门，其它拆迁时间较早和相对没那么知名的商品交易市场是无法搜到的。

无奈之下尝试了一下百度，结果竟然有新发现。以「批发市场」进行关键词检索，首页会发现几个「批发市场平台」，里面汇集了各大批发市场的名录信息。

虽然这些平台乍一看像是山寨的，很多信息就是从网络上粘贴拷贝下来，夹杂着错字和 html 标签。但是名录本身比较齐全。可以依着这些线索，再去找对应市场的具体信息。

还有一个意外是百度百科。多数批发市场都有一个对应着的百度百科条目，里面会有一些市场本身的介绍。

这本来应该是一个常识。但是因为对 google 有着过度的执念，以及对百度搜索有着强烈的抵触，所以竟然完全没有想到要用百度来搜索。

百度百科显示的结果固然不可信，但是可以以此为「关键词线索」，去找新闻报道里面的具体数字。

这种方法其实是基于这样的假设，即新闻报道介绍批发市场的市场规模时会引用百度百科的内容。这是基于以往的经验，结果也不出所料。确实是这样，多数媒体都直接复制了百科的内容。

但是比对二者，无论百度百科还是新闻报道，在介绍规模的时候都没有标注信息来源。

于是就会产生一种非常诡异的感觉。媒体报道和百度百科上的内容完全一样，你明明知道报道中的内容就是复制百科的。但是为了「可信度」，你又需要通过百科找到新闻报道，因为它们才是「可信的来源」。

从中似乎也可以窥见中文互联网世界的某种生态。网络上流传着大量没有出处没有来源的信息，用户不经筛选和甄别地复制粘贴，媒体也概莫能外。

政府方面无论是主管部门还是统计部门没有给民间提供有价值的数据的意识，而行业协会则没有这种能力，即使有也多是粗制滥造。这种生态很糟糕，但是又让人无可奈何。
