---
title: "RSS 订阅方案：Inoreader + Feed43"
date: "2015/12/13"
categories: [工具]
---

按照维基百科的定义，

> RSS（简易信息聚合）是一种消息来源格式规范，用以聚合经常发布更新数据的网站，例如博客文章、新闻、音频或视频的网摘。

用通俗的话说，RSS 就是提供一种信息聚合的服务，能把不同网站不同来源的信息聚合在一处，并以摘要的形式投送给订阅者，以便用户能够对大量信息进行快速筛选和阅读。

## 为何要用 RSS

第一次接触到 RSS 还是大一的时候，是讲座网的一位学长推荐给我们的。那时他在用 Google Reader，我也就跟着注册了一个，添加了十来个订阅源。

不过说实话，作为大一新生，自己每天有意识去获取的信息并不多，因而也就没有养成使用习惯。

直到大二，愈来愈发现自己身上似乎存在着某种程度上的信息饥渴症。每天都要花很多时间在搜寻信息和浏览信息上。而信息源散落又在互联网的各个角落，管理起来比较混乱。

于是又想起了 RSS。但是那时 Google 已经停止了对 Google Reader 的支持，于是就转投 Feedly。一段时间以后就成为了 RSS 的重度用户。

对于一个有着大量信息摄取习惯的人来说，RSS 绝对是利器。它的高效体现在以下几个方面

- 自动投送。节省了用户自己登陆多个网站所花费的时间。

- 及时投送。一般能够在网站发布信息 3 小时内进行投送，付费用户可以确保在 15 分钟内进行投送，这就保证了信息获取的即时性。

- 聚合展示信息。能够让用户快速在信息流中筛选出自己想读的内容，不想读的扫完标题和摘要即可跳过。

- 区分信息的层级。 可以通过给不同的订阅源进行分类来区别信息的重要性。

- 便于保存和查找。遇到优质的内容可以即时保存，添加标签，将来有用时也能很快找到。

- 便于知识管理。可以配合 Evernote 进行使用，形成自己的知识库。

## 微信公众号与 RSS 的异同

其实在某种程度上，微信公众号也可以看成是一个 RSS。公众号运营者通过平台将信息定时定点地投放给订阅者，用户所订阅的信息也都聚合在「订阅号」这个平台上。但是公众号与 RSS 的不同之处在于：

- 公众号加上了「强社交」的色彩，用户除了订阅信息，也在分享信息，也从朋友那里获取信息。我们所获取的信息密度和价值高低，很大程度上取决于我们自己的朋友圈。

- 封闭的系统。信息发布者需要在平台管理方那里进行注册和认证。所有信息也只在平台内部流动。

- 功能较弱。与 Feedly、Inoreader 这类 RSS 订阅器比起来，微信公众号无法区分信息层级，无法进行自定义的信息过滤，无法对自有订阅源进行有效搜索。

综上而言，微信公众号除了社交上的优势外，功能是不如传统的 RSS 订阅器的。

曾经有想过将微信公众号的内容全部推送到自己的 RSS 订阅器上（狗耳朵的付费服务可以实现此功能，详见[此处](http://www.dogear.cn/)）以方便管理，但是发现阅读量、点赞数和评论在网页上都无法查看，于是就放弃了。现在的情况是两边都在用着。

## RSS 订阅器的选择

至于 RSS 订阅器的选择，人各有好。现在比较流行的应用是 Inoreader，我在今年暑假的时候也从 Feedly 迁移到了 Inoreader。理由是 Inoreader 的功能和体验经过不断改进已经全面超越了 Feedly，包括在阅读体验、订阅源管理和社交分享等各方面。

这里有一篇少数派的文章，[《观点：不可替代的 RSS，比 Feedly 更好用的 Inoreader》](http://sspai.com/27576)，比较了两者的优劣。

至于 Inoreader 的使用教程，网络上有非常多的资料，我就不再赘述了。可参看 Inoreader 的[官方教程](http://blog.inoreader.com/p/inoreader-how-to.html?utm_source=inoreader&utm_medium=inoreader&utm_campaign=open_howto_from_gear)，以及这一份简单的[中文入门教程](https://free.com.tw/inoreader/)。

这里要提醒一下，从 10 月份起，Inoreader 的访问速度一下子就变得特别慢。国内网络明明可以访问，但是加载起来需要等待很久的时间。我试了一下让 Inoreader 走代理路线，速度虽然还是比以前慢一些，但是在可接受的范围内。

## RSS 辅助工具「Feed43」的使用

当然，RSS 订阅器也有自己的局限。并不是说有了 RSS 订阅器，就能在互联网上想抓什么抓什么了。如果该网站没有提供 RSS 源，订阅器也无从抓取。比如中国大多数高校网站和政府网站就不提供 RSS 源。

但是如果真有需求，我们完全可以使用一些工具来自己制作订阅源。[Feed43](http://feed43.com/) 就是这样一款优秀的定制工具，只需要稍懂一些 html，我们即可进行高度的个性化定制。
