---
title: "Scrapy 学习感想及资源汇集"
date: "2015/11/20"
categories: [Python, 爬虫, 清单]
---

最近一段时间一直在学 Python，想通过 Python 来写一些有趣的小爬虫。

其实就语法来说，如果有了一定的 Javascript 基础，Python 的语法学起来并不会很困难。真正困难的是怎样配置运行环境，以及怎样在遇到 bug 的时候进行有效排查。

在学 Requests 库的时候尚不会觉得很吃力，因为文档的内容本身比较少，遇到问题多调试几下也就解决了。但是学习 Scrapy，对于一个像我这样的 Python 初学者而言，单单看 Scrapy 的文档还是很困难的。

首先是文档本身很长，并且里面有很多生僻的概念。第一次遇到这些概念，无论是中英文都读不太懂。

其次是 Scrapy 调试起来比较困难（当然是相较于 Requests 而言的），很多时候遇到问题也不知道如何解决。

最后是学习 Scrapy 要涉及到很多的知识领域，而且这些都是之前自己并没有接触过的。在学的过程中会发现，原来不仅仅要学习 Python，还要学 HTTP 协议，要学习 Xpath，要学习正则表达式，甚至还要学习 Linux。

我原先用的是 Windows 的开发环境，在安装以及调试的时候遇到了各种问题，好不容易安装成功却发现 Scrapy shell 无法使用。无奈之下安装了一个 VitualBox 虚拟机，在 Linux 下进行开发。

虽然学习 Linux 基础也花了很多时间（慕课网上有非常好的视频教程，Tony 老师的讲得特别棒，链接[见此](http://www.imooc.com/space/teacher/id/279399)），但是现在想起来绝对是超值。因为学 Linux 可以加深我们对计算机系统的理解。

所以，一路学下来的过程还是比较坎坷的，也曾几度想要放弃，但好歹坚持下去了。虽然现在看文档还是有一大部分不能理解，但是至少是能爬点东西下来了。

所以就想把自己在学习过程中遇到的好东西整理出来，以后再找起来也就没那么费力。

## HTTP 基础

- [图解HTTP](http://book.douban.com/subject/25863515/) 可以了解 HTTP 协议的基础知识和概念，写得挺通俗的一本书

## Xpath
用 Xpath 可以简单地进行结构化的网页数据提取

- [W3School 教程](http://www.w3school.com.cn/xpath/)

- [极客学院：XPath 与多线程爬虫](http://www.jikexueyuan.com/course/902.html)

## 正则表达式
当遇到比较复杂的网页内容时，可以用正则表达式进行精确地字符串匹配。但是正则学习起来还是很复杂的，到现在我也只能做简单的匹配。从视频入门可能会相对容易一些。

- [极客学院：基本的正则表达式](http://www.jikexueyuan.com/course/777.html)

- [慕课网：Python 正则表达式](http://www.imooc.com/learn/550)

- [Python 正则表达式指南](http://www.cnblogs.com/huxi/archive/2010/07/04/1771073.html)

- [Ubuntu：Python 正则表达式操作指南](http://wiki.ubuntu.org.cn/Python%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F%E6%93%8D%E4%BD%9C%E6%8C%87%E5%8D%97)

## Scrapy 文档

虽然文档很难读，但是还是最重要的参考资料

- [中文文档0.24](https://scrapy-chs.readthedocs.org/zh_CN/0.24/)

- [英文文档0.24](http://doc.scrapy.org/en/0.24/)

## Scrapy 的相关视频

没有相关基础的话可以先从视频入手。极客学院 kingname 老师讲课的语速虽然偏慢，但是逻辑还是很清晰的。课程有提供源码，按照里面的步骤自己操作一遍，会很有收获。

- [极客学院：定向爬虫：Scrapy初探](http://www.jikexueyuan.com/course/1287.html)

- [极客学院：定向爬虫：MongoDB与Scrapy](http://www.jikexueyuan.com/course/1439.html)

- [极客学院：定向爬虫：动态加载网页的爬取](http://www.jikexueyuan.com/course/1713.html)

## Scrapy 的相关文章
首推 young-hz 在 CSDN 上写的系列文章，通读一遍，会对 Scrapy 的结构和运作机制有一个比较清楚的了解

- [Scrapy 研究探索（一）——基础入门](http://blog.csdn.net/u012150179/article/details/32343635)

- [Scrapy 研究探索（二）——爬w3school.com.cn](http://blog.csdn.net/u012150179/article/details/32911511)

- [Scrapy研究探索（三）——Scrapy核心架构与代码运行分析](http://blog.csdn.net/u012150179/article/details/34441655)

- [Scrapy研究探索（四）——中文输出与中文保存](http://blog.csdn.net/u012150179/article/details/34450547)

- [Scrapy研究探索（五）——自动多网页爬取（抓取某人博客所有文章）](http://blog.csdn.net/u012150179/article/details/34486677)

- [Scrapy研究探索（六）——自动爬取网页之II（CrawlSpider）](http://blog.csdn.net/u012150179/article/details/34913315)

- [Scrapy研究探索（七）——如何防止被ban之策略大集合](http://blog.csdn.net/u012150179/article/details/35774323)

然后还有其它一些不错的文章

- [学习Scrapy入门](http://www.jianshu.com/p/a8aad3bf4dc4)

- [爬虫框架Scrapy的第一个爬虫示例入门教程](http://blog.csdn.net/pleasecallmewhy/article/details/19642329)

- [Scrapy模拟登录](http://www.jianshu.com/p/b7f41df6202d)

- [Scrapy笔记—微博模拟登录及抓取微博内容](http://www.jianshu.com/p/36a39ea71bfd)

- [使用Scrapy定制可动态配置的爬虫](http://wuchong.me/blog/2015/05/22/running-scrapy-dynamic-and-configurable/)

- [编程方式下运行 Scrapy spider](http://wuchong.me/blog/2015/05/22/running-scrapy-programmatically/)

- [使用Redis和SQLAlchemy对Scrapy Item去重并存储](http://wuchong.me/blog/2015/05/22/using-redis-and-sqlalchemy-to-checkd-dup-and-store-scrapy-item/)

## Scrapy 案例

- [scrapy-examples](https://github.com/geekan/scrapy-examples)
github 上的开源项目，里面有知乎、豆瓣、亚马逊等十个网站的爬虫源码，可以模仿学习。