---
title: "全局代理方案：土行孙 + Proxifier"
date: "2016/03/28"
categories: [科学上网]
---

多数时候，科学上网的目的是为了在 Web 上浏览墙外信息，比如上 Twitter、Facebook 及各类新闻网站，而这一行为基由浏览器即可完成。

所以，一般情况下，我们只要购买一个 HTTP 代理帐号，给浏览器装上插件，就可以实现自由上网。我自己使用的是[土行孙](https://itxs.in)。

但是，当需求变得复杂，比如需要让桌面上的软件也实现代理的时候，就会遇到一些困难和障碍。比如我自己就曾遇到过以下问题：

- 墙内无法使用桌面版的 [import.io](https://import.io) 抓取网页数据

- zotero 无法调用 google scholar 的 API 更新论文的被引用次数

- excel 无法调用 google map 的 API 获取给定地点的经纬坐标

其实，不少常用软件，如 Dropbox，在「设置」或「首选项」的选项卡内都会内置有代理功能，我们只需要在相关界面内填入自己的代理服务器、帐号和密码即可实现软件代理。

但是对于那些没有代理功能的软件，像上面提到的 import.io 和 zotero，我们很多时候就无能为力了。

为了使用这些软件，以前我会使用[赛风](https://psiphon.ca/zh/download.html)这样具有全局代理功能的 VPN。但是由于筑墙技术的不断进步，赛风越来越不稳定，每次用这种方法都会非常耗时费力。

后来在网上寻找解决方案的时候发现了一款叫 Proxifier 的软件，惊喜地发现它不仅可以实现网络的全局代理，还可以根据自己的需要让指定的软件实现代理功能。具体步骤如下：

## 注册土行孙帐号

对于常用 HTTP 代理的选择，强烈推荐[土行孙](https://itxs.in)，它有很多优点。

- 服务稳定。用了三个多月，唯一的一次故障通过网站自带的「服务自检」功能立刻解决了。

- 跨平台、多设备支持。基本套餐有 20G 的流量，用完为止，不限同时在线的设备数量。

- 智能分流。能自动识别流量，需要翻墙就走代理，不需要翻墙就直接访问。如果遇到不能识别的网站，可以手动添加网址。

- 配置方便。除了可以很方便地代理浏览器，还可以代理终端，甚至可以配置 AnyConnect 和 Surge

当然，用其它的 HTTP 代理或者 SOCKS 代理配合 Proxifier 应该也能够实现同样的功能，但是我没有试过。

## 下载安装 Proxifier
[下载地址](https://www.proxifier.com/download.htm)

## 配置 Proxifier

### 设置代理服务器

- 点击菜单栏中的 Profile - Proxy Servers

- 点击 Add 添加并配置代理服务器

- 填写服务器地址（Address）和端口（Port）

- 选择代理的协议类型，土行孙为 HTTPS

- 在Authentication下选中 Enable

- 填写代理的帐号（Username）密码（Password）

- 点击确定

### 设置代理规则

- 点击设置代理规则的图标 Proxification Rules

- 规则中有两个默认的设置，分别是 Localhost 和 Default 。如果需要实现全局代理，则将 Default 的 Action 从 Direct 改为代理服务器

- 点击Add添加规则，在 Name 中填写规则名称，在 Applications 中添加软件的路径，最后在 Action 选中代理服务器即可

现在打开应用软件，软件已经可以走代理了。日志中还可以查看到代理应用每次发起的网络请求。
